vich_uploader:
  db_driver: orm
  metadata:
    type: attribute
  mappings:
    product_pictures:
      uri_prefix: '%app.path.product_pictures%'
      upload_destination: '%kernel.project_dir%/public%app.path.product_pictures%'
      namer: Vich\UploaderBundle\Naming\HashNamer
      inject_on_load: true
